/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnswerLogRouteImport } from './routes/answer-log'
import { Route as AssistantMapRouteImport } from './routes/assistant-map'
import { Route as ClientSitesRouteImport } from './routes/client-sites'
import { Route as KnowledgeBaseRouteImport } from './routes/knowledge-base'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as KnowledgeBaseIndexRouteImport } from './routes/knowledge-base.index'
import { Route as KnowledgeBaseProgramIdRouteImport } from './routes/knowledge-base.$programId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnswerLogRoute = AnswerLogRouteImport.update({
  id: '/answer-log',
  path: '/answer-log',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantMapRoute = AssistantMapRouteImport.update({
  id: '/assistant-map',
  path: '/assistant-map',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSitesRoute = ClientSitesRouteImport.update({
  id: '/client-sites',
  path: '/client-sites',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseRoute = KnowledgeBaseRouteImport.update({
  id: '/knowledge-base',
  path: '/knowledge-base',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeBaseIndexRoute = KnowledgeBaseIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => KnowledgeBaseRoute,
} as any)
const KnowledgeBaseProgramIdRoute = KnowledgeBaseProgramIdRouteImport.update({
  id: '/$programId',
  path: '/$programId',
  getParentRoute: () => KnowledgeBaseRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/answer-log': typeof AnswerLogRoute
  '/assistant-map': typeof AssistantMapRoute
  '/client-sites': typeof ClientSitesRoute
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/knowledge-base/$programId': typeof KnowledgeBaseProgramIdRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/answer-log': typeof AnswerLogRoute
  '/assistant-map': typeof AssistantMapRoute
  '/client-sites': typeof ClientSitesRoute
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/knowledge-base/$programId': typeof KnowledgeBaseProgramIdRoute
  '/knowledge-base': typeof KnowledgeBaseIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/answer-log': typeof AnswerLogRoute
  '/assistant-map': typeof AssistantMapRoute
  '/client-sites': typeof ClientSitesRoute
  '/knowledge-base': typeof KnowledgeBaseRouteWithChildren
  '/pipeline': typeof PipelineRoute
  '/reports': typeof ReportsRoute
  '/knowledge-base/$programId': typeof KnowledgeBaseProgramIdRoute
  '/knowledge-base/': typeof KnowledgeBaseIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/answer-log'
    | '/assistant-map'
    | '/client-sites'
    | '/knowledge-base'
    | '/pipeline'
    | '/reports'
    | '/knowledge-base/$programId'
    | '/knowledge-base/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/answer-log'
    | '/assistant-map'
    | '/client-sites'
    | '/pipeline'
    | '/reports'
    | '/knowledge-base/$programId'
    | '/knowledge-base'
  id:
    | '__root__'
    | '/'
    | '/answer-log'
    | '/assistant-map'
    | '/client-sites'
    | '/knowledge-base'
    | '/pipeline'
    | '/reports'
    | '/knowledge-base/$programId'
    | '/knowledge-base/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnswerLogRoute: typeof AnswerLogRoute
  AssistantMapRoute: typeof AssistantMapRoute
  ClientSitesRoute: typeof ClientSitesRoute
  KnowledgeBaseRoute: typeof KnowledgeBaseRouteWithChildren
  PipelineRoute: typeof PipelineRoute
  ReportsRoute: typeof ReportsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/answer-log': {
      id: '/answer-log'
      path: '/answer-log'
      fullPath: '/answer-log'
      preLoaderRoute: typeof AnswerLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant-map': {
      id: '/assistant-map'
      path: '/assistant-map'
      fullPath: '/assistant-map'
      preLoaderRoute: typeof AssistantMapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-sites': {
      id: '/client-sites'
      path: '/client-sites'
      fullPath: '/client-sites'
      preLoaderRoute: typeof ClientSitesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base': {
      id: '/knowledge-base'
      path: '/knowledge-base'
      fullPath: '/knowledge-base'
      preLoaderRoute: typeof KnowledgeBaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge-base/': {
      id: '/knowledge-base/'
      path: '/'
      fullPath: '/knowledge-base/'
      preLoaderRoute: typeof KnowledgeBaseIndexRouteImport
      parentRoute: typeof KnowledgeBaseRoute
    }
    '/knowledge-base/$programId': {
      id: '/knowledge-base/$programId'
      path: '/$programId'
      fullPath: '/knowledge-base/$programId'
      preLoaderRoute: typeof KnowledgeBaseProgramIdRouteImport
      parentRoute: typeof KnowledgeBaseRoute
    }
  }
}

interface KnowledgeBaseRouteChildren {
  KnowledgeBaseProgramIdRoute: typeof KnowledgeBaseProgramIdRoute
  KnowledgeBaseIndexRoute: typeof KnowledgeBaseIndexRoute
}

const KnowledgeBaseRouteChildren: KnowledgeBaseRouteChildren = {
  KnowledgeBaseProgramIdRoute: KnowledgeBaseProgramIdRoute,
  KnowledgeBaseIndexRoute: KnowledgeBaseIndexRoute,
}

const KnowledgeBaseRouteWithChildren = KnowledgeBaseRoute._addFileChildren(
  KnowledgeBaseRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnswerLogRoute: AnswerLogRoute,
  AssistantMapRoute: AssistantMapRoute,
  ClientSitesRoute: ClientSitesRoute,
  KnowledgeBaseRoute: KnowledgeBaseRouteWithChildren,
  PipelineRoute: PipelineRoute,
  ReportsRoute: ReportsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
